



Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 6   Second client= /cgi-bin/env.sh
first client = 7   Second client= 

first = 8   Second = 8
socket = 6
cgi socket = 8
reseted the cgi client request
size after = 2
handleClientResponse
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 6   Second client= /cgi-bin/env.sh
first client = 7   Second client= 

first = 8   Second = 8
socket = 6
cgi socket = 8
reseted the cgi client request
size after = 2
handleClientResponse
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 6   Second client= /cgi-bin/env.sh
first client = 7   Second client= 

first = 8   Second = 8
socket = 6
cgi socket = 8
reseted the cgi client request
size after = 2
handleClientResponse
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 6   Second client= /cgi-bin/env.sh
first client = 7   Second client= 

first = 8   Second = 8
socket = 6
cgi socket = 8
reseted the cgi client request
size after = 2
handleClientResponse
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 6   Second client= /cgi-bin/env.sh
first client = 7   Second client= 

first = 8   Second = 8
socket = 6
cgi socket = 8
reseted the cgi client request
size after = 2
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 6   Second client= /cgi-bin/env.sh
first client = 7   Second client= 

first = 8   Second = 8
socket = 6
cgi socket = 8
reseted the cgi client request
size after = 2
handleClientResponse
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 6   Second client= /cgi-bin/env.sh
first client = 7   Second client= 

first = 8   Second = 8
socket = 6
cgi socket = 8
reseted the cgi client request
size after = 2
handleClientResponse
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 6   Second client= /cgi-bin/env.sh
first client = 7   Second client= 

first = 8   Second = 8
socket = 6
cgi socket = 8
reseted the cgi client request
size after = 2
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 1
first client = 7   Second client= 

first = 8   Second = 8
socket = 6
cgi socket = 8
size after = 1




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 1
first client = 7   Second client= /cgi-bin/env.sh

first = 6   Second = 6
socket = 7
cgi socket = 6
reseted the cgi client request
size after = 1
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 7   Second client= /cgi-bin/env.sh
first client = 8   Second client= 

first = 6   Second = 6
socket = 7
cgi socket = 6
reseted the cgi client request
size after = 2
handleClientResponse
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 7   Second client= /cgi-bin/env.sh
first client = 8   Second client= 

first = 6   Second = 6
socket = 7
cgi socket = 6
reseted the cgi client request
size after = 2
handleClientResponse
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 7   Second client= /cgi-bin/env.sh
first client = 8   Second client= 

first = 6   Second = 6
socket = 7
cgi socket = 6
reseted the cgi client request
size after = 2
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
ci res = FirstName = 
SecondName = 
CGI Information :
FILENAME = /Users/atukka/Desktop/cursus/webserve_par/content/cgi-bin/env.sh
QUERY_STRING = 
HTTP_USER_AGENT =  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
REQUEST_METHOD = GET
SERVER_NAME = localhost:9090
CONTENT_TYPE = 
CONTENT_LENGHT = 
hi
hi

size = 2
first client = 7   Second client= /cgi-bin/env.sh
first client = 8   Second client= 

first = 6   Second = 6
socket = 7
cgi socket = 6
reseted the cgi client request
size after = 2
handleClientResponse
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
handleClientResponse




Parsed successfully
fall = 
user agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Error While Opening The Body File
doe cgi
processGetRequest
parseHeaders
done processIncomingData
handling handleClientRequest
